= Dokumentation LPIC 1
:toc:

== Kommandos

* `whoami` - Gibt den aktuellen Benutzer aus
* `pwd` _Present Working Directory_ - Gibt den absoluten Pfad des aktuellen Verzeichnisses an
* `ls` - Gibt den Inhalt des aktuellen Verzeichnisses aus
* `ls -a` - Gibt den Inhalt des aktuellen Verzeichnisses aus, _alles_, inkl. der versteckten Dateien/Verzeichnisse
* `ls -l` - Gibt den Inhalt des aktuellen Verzeichnisses aus, mit zusätzlichen Informationen zu den Dateien
* `cd` - _Change Directory_ - Wechselt in das angegebene Verzeichnis, ohne Optionen direkt in das Heimatverzeichnis
* `clear` - Leert den Bildschirm (`STRG+L`)
* `mkdir` - erstellt ein Verzeichnis
* `touch` - kann leere Dateien erstellen
* `cat` - Gibt den Inhalt von Dateien aus
* `rm` - löscht Dateien
* `date` - gibt das aktuellen Datum und Uhrzeit aus
* `date '+%d.%m.%Y'` git das Datum in folgendem Format aus: `16.05.2023`

== Hilfe auf der Kommandozeile

=== Manpages

 man <kommando>

== Sonderzeichen

=== Globbing Characters

Die Shell versucht immer, diese Sonderzeichen zu interpretieren

* `*` - Asterisk - steht für ein beliebiges Zeichen, dass *beliebig oft* vorkommen darf
* `?` - Fragezeichen - steht für ein beliebiges Zeichen, dass *exakt einmal* vorkommen darf
* ` ` - Leerzeichen - ist das *Trennzeichen*, trennt z.B. Kommando von Optionen und oder Argumenten etc.

== Maskieren / Escaping von Sonderzeichen

* `\` - Backslash - verhindert, dass die Shell das direkt darauf folgende Zeichen interpretiert
* alternativ können Sonderzeichen auch in einfache (`'`) oder doppelte (`"`) Anführungszeichen eingefasst werden
* es gibt einen Unterschied zwischen einfachen und doppelten Anführungszeichen

== Pfadangaben

=== absolut

Wegbeschreibung vom Wurzelverzeichnis `/` bis zum Ziel

 cd /home/tux/spielwiese/viele-dateien

=== relativ

Wegbeschreibung vom aktuellen Verzeichnis aus bis zum Ziel

 cd /home/tux/spielwiese
 cd viele-dateien

== Variablen

Erstellung einer Variablen und Zuweisung eines Wertes:

 my_var=hallo

Ausgabe des Inhalts einer Variablen (_Variablensubstitution_):

 echo $my_var

Das Dollarzeichen (`$`) ist wieder ein Sonderzeichen. Es weist die Shell an, eine _Substitution_ (Ersetzung) durchzuführen.

Variablen sind immer nur in der *aktuellen* Shell gültig, nicht in z.B. _Subshells_, also Shells, die innerhalt der aktuellen Shell laufen.

Will man Variablen auch in Subshells verfügbar machen, so muss man diese _exportieren_:

 export my_env_var=überall

 my_var=hallo
 export my_var

Variablen sind so lange gültig, wie die Shell existiert, in der sie definiert wurden.

Variablen können mit `unset` gelöscht werden:

 unset my_var

== History

Alle eingegebenen Kommandos werden in der _history_ gespeichert. Zuerst im Speicher und letztlich beim Beenden der Shell in der Datei `~/.bash_histroy`.

Einige wichtige Kommandos dazu:

* `history` ruft die gesamte history auf
* `history <anzahl>` zeigt nur die <anzahl> der letzten Einträge auf
* `!!` führt das letzte Kommanod erneut aus
* `!<zahl>` führt Kommando mit index <zahl> aus
* `!<zeichenfolge>` führt letztes Kommando aus, das mit `<zeichenfolge>` beginnt 
* `!?<zeichenfolge>` führt letztes Kommando aus, das `<zeichenfolge>` enthält
* `!$` repräsentiert das letzte Argument des zuletzt eingegebenen Kommandos

== Dateioperationen

* `mkdir verz` erstellt das Verzeichnis `verz`
* `cp quelle ziel` kopiert Datei `quelle` nach `ziel` (`ziel` kann/muss aber nicht existieren. Falls `ziel` existiert, wird die Datei *ohne Nachfrage* überschrieben
* `cp -r quell_verz ziel_verz` kopiert das *Verzeichnis* `quell_verz` in das Zielverzeichnis `ziel_verz`
* `mv quelle ziel` verschiebt `quelle` nach `ziel` (egal ob Datei oder Verzeichnis)
* `rm datei` löschte `datei` (ohne Nachfrage)
* `rm -r verz` löscht `verz` inkl. Inhalt
* `rmdir verz` löscht das *leere* Verzeichnis `verz`


== Aliase

Abkürzungen für z.B. längere/häufig benutzte Kommandos

 alias ll='ls -l'

Alias löschen:

 unalias ll

Alle Aliase anzeigen:

 alias

Aliase können persistent konfiguriert werden, z.B. in der Datei `~/.bashrc` bzw. in `~/.bash_aliases`

Nach Änderungen muss die Datei `~/.bashrc` neu eingelesen werden. Dies geschieht automatisch beim Start einer neuen BASH oder alternativ mit dem Kommanod `source` bzw. dessen Abkürzung `.`

 source ~/.bashrc
 . ~/.bashrc

== Konfigurationsdateien

=== Benutzerspezifische 

* beginnen immer mit einem Punkt bzw. befinden sich in einem Verzeichnis, das mit einem Punkt beginnt
* sind immer im Heimatverzeichnis des Nutzers

=== Systemweite

* alle systemweiten Konfigurationsdateien befinden sich im Verzeichnis `/etc`

== Textströme

=== UNIX Philosophie

1. Schreibe Programme so, dass sie *eine* Aufgabe erledigen und diese gut machen
2. Schreibe Programme so, dass sie zusammenarbeiten
3. Schreibe Programme so, dass sie Textströme verarbeiten, denn Text ist eine universelle Schnittstelle

Vereinfacht gesagt: Mache eine Sache und mache diese gut (KISS Prinzip)

* KISS: Keep it simple, stupid!
* KISS: Keep it stupid simple
* KISS: Keep it super simple

=== Standardkanäle

* `stdin` - Standardeingabekanal - `0`
* `stdout` - Standardausgabekanal - `1`
* `stderr` - Standardfehlerkanal - `2`

== Redirect

* Kanäle können umgeleitet werden, entweder in Dateien oder andere Kommandos
* `kommando 1>datei`: Ausgabe von `kommando` wird in Datei umgeleitet, Inhalt der Datei wird ersetzt
* `kommando > datei`: gleich wie oben, `1` kann weggelassen werden
* `kommando >> datei`: gleich wie oben, Inhalt wird an Datei angehängt
* `kommando < datei`: Inhalt von datei wird an die Standardeingabe von Kommando gesendet/umgeleitet
* Sowohl Ausgabe als auch Fehler in gleiche Datei leiten: `kommando >textdatei 2>&1` bzw. `kommando >& textdatei`
* `kommando1 | kommando2`: die Ausgabe (Kanal 1) von `kommando1` wird an die Eingabe (Kanal 0) von `kommando2` geleitet

== Filterkommandos

Textströme können mit Filterkommandos bearbeitet werden, so dass die Information, die uns interessiert, herausgefiltert werden kann.

* `cut`: schneidet Spalten aus tabellarisch aufgebauten Dateien aus (`cut -d: -f1 /etc/passwd`: nur die Benutzernamen ausgeben)
* `tail`: gibt die letzen (Standarmässig 10) Zeilen einer Datei aus (`tail -n5 /etc/passwd`: gibt die letzten 5 Zeilen der `passwd` aus)
* `grep`: sucht nach einem Suchbegriff innerhalb von Dateien/Textströmen und gibt die entsprechende Zeile aus (`grep bash /etc/passwd`: gibt alle Zeilen aus, in denen der String `bash` vorkommt)
* `grep -i <pattern>`: Gross- und Kleinschreibung von `<pattern>` ist egal
* `grep -n <pattern>`: Anzeige der Zeilennummer, in der `<pattern>` gefunden wurde
* `grep -r <pattern> dir/`: Rekursive Suche, so kann über alle Dateien in einem Verzeichnis _gegrept_ werden
* `grep -v <pattern>`: _inVert match_: Ausgabe wird _invertiert_, also nur die Zeilen ausgegeben, in denen `<pattern>` *nicht* vorkommt
* `tr`: übersetzt ein Zeichen in einem Textstrom (es können keine Dateien als Argument übergeben werden) in ein anderes/löscht dieses etc... (`tr a A < datei.txt`: wandelt jedes kleine `a` in ein grosses `A` um)
* `wc`: gibt die Anzahl der Zeilen, Wörter und Bytes einer Datei an (`wc -l /etc/passwd`: Anzahl Zeilen der Datei `/etc/passwd`)
* `tee`: verzweigt den Textstrom, so dass sowohl eine Ausgabe erfolgt, als auch in eine Datei geschrieben werden kann (`ls /etc | tee ls-etc.txt`)

== Kommandosubstitution

* `$(kommando)`: `kommando` wird (in einer Subshell) ausgeführt und durch sein Ergebnis ersetzt: 
  * Bsp.: Unterschied von `var=date` gegenüber `var=$(date)`:  
  
----
var=date
echo $var
> date   # String/Zeichenkette date wird ausgegeben
----

----
var=$(date)
echo $var
> Tue May 23 03:42:43 PM CEST 2023   # aktuelles Datum wird ausgegeben
----

Ältere Syntax für die Kommandosubstitution, Kommando wird in Backticks (```) eingefasst:

----
var=`date`
echo $var
> Tue May 23 03:42:43 PM CEST 2023   # aktuelles Datum wird ausgegeben
----

== echo

* `echo -e`: so kann `echo` gewisse Steuerungszeichen interpretieren, um z.B. einen Zeilenumbruch zu erzeugen, einen horizontalen oder vertikalen Tabulator, ein Backspace etc.
* diese Steuerungszeichen / Sequenzen beginnen mit einem `\` (Backslash)
* `echo -e '\n'`: echo gibt eine (zusätzliche) Leerzeile aus (echo an sich führt bereits einen Zeilenumbruch am Ende der Ausgabe aus, so erhalten wir also zwei Leerzeilen) 
* `\n` muss in diesem Fall _escaped/maskiert/gequotet_ werden, damit nicht die BASH, sondern das Kommando an sich (`echo`) den Backslash als Sonderzeichen interpretieren kann
* der Backslash muss sozusagen vor der Shell "versteckt" werden
* das Escapen kann sowohl durch Einfassen in einfache oder doppelete Anführungszeichen (`'` oder `"`) erfolgen, oder durch die Voranstellung eines Backslashs (`\`)

 echo -e '\n'
 echo -e "\n"
 echo -e \\n

* Unterschied von einfachen und doppelten Anführungszeichen bei der Substitution mit `$`:

 my_var=hallo
 echo '$my_var'
 > $my_var

 echo "$my_var"
 > hallo

=== Beispiele Kommandosubstitution und echo

 echo -e "Hallo, ich bin $(grep ${USER} /etc/passwd | cut -d: -f5 | cut -d, -f1).\n\nHeute ist der $(date '+%d.%m.%Y, %H:%M')." > username.txt

 echo -e "Hallo, ich bin $(grep $(whoami) /etc/passwd | cut -d: -f5 | cut -d, -f1).\n\nHeute ist der $(date '+%d.%m.%Y, %H:%M')." > username.txt

== Dateisystembaum unter Linux

Filesystem Hierarchy Standard - FHS: Eine Empfehlung an alle Distributionen, wie der Dateisystembaum unter UNIX/Linux aufgebaut sein sollte.

- `/bin`: common executables available for everyone, `ex. cp rm ls`
- `/boot`: kernel and boot configuration, initial ramdisk, kernel image
- `/dev`: files which point to both physical and pseudo devices, populated by `udev`
- `/etc`: systemwide configuration files
- `/home`: non-root user home directories
- `/lib`: library files used by the system, include `.so` files and others
- `/lib32`: library files used by the system, include `.so` files and others
- `/lib64`: library files used by the system, include `.so` files and others
- `/lost+found`: saved files due to failure, not relevant for users, just for the system
- `/media`: auto-mounting place for certain external devices on some distros
- `/mnt`: place to mount various file systems
- `/opt`: various software, not installed by package manager
- `/proc`: virtual filesystem (`procfs`) for resources, processes, and more, only in memory, not actual files on hard disk
- `/root`: root user home directory
- `/sbin`: similar to `/bin`, but for system administrators, ex. `fdisk`
- `/tmp`: temporary file storage, wiped out after reboot
- `/usr`: user programs, library files, docs, etc.
- `/var`: variable files for various purposes, ex. logs, tz data, files for webserver (debian)
- `/vmlinuz`: boot/vmlinuz-4.15.0-43-generic: compressed linux kernel 

=== weitere wichtige Verzeichnisse (nicht Bestandteil des FHS)

- `/sys`: virtual filesystem (`sysfs`), extension to `/proc`
- `/run`: virtual filesystem, was under `/var/run` (symlinked) before, applications can store data needed to operate, e.g. `.lock` files

== Prozesse

Ein Programm resultiert immer in mindestens einem Prozess. Prozesse laufen jeweils in einem von anderen unabhängigen "Resourcenraum", haben eine eigene PID, kennen nur die PID des Prozesses, von dem sie gestartet wurden (Elternprozess). Prozesse können mit dem Kommando `kill` über _Signale_ beeinflusst werden.

Auf der Shell kann immer nur ein einzelner Prozess im Vordergrund ausgeführt werden. Prozesse können mit der Tastenkomnination `STRG+Z` angehalten und in den Hintergrund geschickt werden. Mit dem Kommando `bg` kann dieser Prozess dann im Hintergund fortgesetzt werden, `fg` holt den Prozess in den Vordergrund zurück.

* `ps -aux`: Anzeige aller laufende Prozessez
* `ps -ef`: auch Anzeige aller laufenden Prozesse
* `ps --forest`: Prozesshirarchie (Baumstruktur) anzeigen
* `jobs`: Anzeigen der Hintergrundprozesse
* `jobs %<jobnummer>`: bestimmten Job ansprechen
* `fg`: letzten/aktuellen/default Job in den Vordergrund holen
* `fg %<jobnummer>`: Job mit Jobnummer `<jobnummer>` in den Vordergrund holen
* `bg`: Hintergrundprozess fortsetzen
* `bg %<jobnummer>`: Hintergrundprozess mit Jobnummer `<jobnummer>` in fortsetzen
* `kill`: sendet Siganle an Prozesse 
* `kill -s <signal> <PID>`: sendet <signal> an Prozess mit der PID <PID>
* `kill -<signal> <PID>`: sendet <signal> an Prozess mit der PID <PID>
* `pkill`: analog zu oben, `pkill` erwartet aber den Namen bzw. einen Teil des Namesns eines Prozesses anstatt der PID
* `killall`: wie oben, erwartet aber den exakten Prozessnamen
* `pgrep`: PID laufender Prozesse ermitteln, ähnlich wie `ps -ef | grep`
* `nohup`: aufgerufener Prozess wird von der aufrufenden Shell gelöst, so dass dieser Prozess auch weiterläuft, wenn die aufrufenden Shell beendet wird
* `nohup ping 1.1.1.1 &`: Ausgabe von `ping` in Datei `nohup.out` umleiten und von der aufrufenden Shell lösen
* `tail -f`: fortlaufende Beobachtung einer Datei (neue Einträge werden automatisch angezeigt)
* `top`: Anzeige laufender Prozesse, ähnlich zum Taskmanager unter Windows, Prozesse können auch interaktiv beeinflusst werden
* `htop`: komfortablere Variante von `top`

=== Ausfühungsprioritäten Prozesse

* es gibt normale Prozesse und realtime Prozesse
* realtime Prozesse haben Prioritäten zwischen 0 und 99
* normale Prozesse haben Prioriäten zwischen 100 und 139
* Standardpriorität ist 120
* je geringer die Priorität ist, desto mehr CPU Leistung bekommt ein Prozess
* `ps` zeigt Prioritäten von -40 bis 99, wir addieren also immer 40 dazu
* `top` zeigt Prioritäten von -100 bis 39, wir addieren also immer 100 dazu
* `nice` kann einem Kommando beim Start eine geringere/höhere Ausführungspriorität zuweisen
  * Werte von -20 bis -1 koennen nur von `root` zugewiesen werden
  * Werte von 0 bis 19 von normalen Benutzern
  * ein hoeherer `nice` - Wert bedeute, dass der Prozess eine *geringere* Ausführungspriorität zugewiesen bekommt (Prozess ist _nicer/netter_ zu anderen Prozessen)
* `renice` kann einem Kommando im laufenden Betrieb eine andere Priorität zuweisen
* nur `root` kann `renice` ausführen

== Benutzer und Gruppen

Es gibt zwei Arten von Benutzern:

* Systembenutzer/Pseudobenutzer
* Reale Benutzer

=== Dateien der Benutzerverwaltung

* `/etc/passwd`: Liste aller Benutzer auf dem System, tabellarischer Aufbau, Manpage `man 5 passwd`, von allen lesbar
* `/etc/shadow`: Passwörter der Benutzer, gesaltet und gehasht, Ablaufdaten der Passwörter
* `/etc/group`: Liste aller Gruppen und deren Mitglieder
* `/etc/gshadow`: Passwörter für Gruppen, wird eigentlich nicht verwendet

=== Benutzer anlegen

 useradd karl
  
Obiges Kommando erzeugt den Benutzer `karl`, es wird jedoch kein Heimatverzeichnis erstellt und die Shell ist die `/bin/sh`

Mit folgendem Kommando wird der Benutzer `tux` mit eigenem Heimatverzeichnis und darin enthaltener Standarddateien (Kopie von `/etc/skel`) erzeugt, im Kommentarfeld der Name `Tux Tuxedo` und der BASH als Login Shell:

 useradd -m -c 'Tux Tuxedo' -s /bin/bash tux

Anschließend muss mit dem Kommando `passwd tux` noch ein Passwort für `tux` erstellt werden.

Das interaktive Kommando `adduser` unter Debian ist ein Wrapper um `useradd`, welches zusätzlich ein Passswort erstellt.

=== Benutzer ändern

Mit dem Kommando `usermod` können Eigenschaften von Benutzern geändert werden. Die Optionen sind sehr ähnlich zu `useradd`.

=== Gruppen anlegen

Gruppe `gfn` erzeugen:

 groupadd gfn

Benutzer `tux` der Gruppe `gfn` hinzufügen:

 usermod -aG gfn tux

Wichtig ist hier das `-a`, ansonsten werden alle anderen Gruppenzugehörigkeiten von `tux` gelöscht.

Gruppenzugehörigkeiten werden erst aktiv, wenn sich der Benutzer einmal komplett vom System ab- und wieder angemeldet hat.

=== Benutzer wechseln

`su tux`: Wechselt in den Benutzeraccount von `tux`, Umgegung (env, Variablen etc.) werden teilweise neu gesetzt. 
`su - tux`: wie oben, es werden aber alle Umgebungsvariablen neu gesetzt ("echte" Login Shell)
`su -l tux`: wie oben
`su --login tux`: wie oben

=== Besitzer ändern

 chown user <datei>

=== Gruppe ändern

 chgrp group <datei>

 chown :group <datei>

=== Besitzer und Gruppe ändern

 chown user:group <datei>

== Dateibereichtungen


 r : read 
 w : write
 x : execute


 User Group Others
 rw-  r--   r--


== Berechtigungen setzen

=== Symbolische Rechtevergabe

 chmod g+w <datei>   # Schreibrecht für Gruppe hinzufügen

 chmod u-w <datei>   # Schreibrecht für User entziehen

 chmod go-rx <datei>   # Schreibrecht und Ausführungsrecht für Others und Gruppe entziehen

 chmod u=rwx <datei>  # alle Rechte für Owner setzen

=== Oktale/Numerische Rechtevergabe

 r : read     4
 w : write    2
 x : execute  1

       ugo
 chmod 220 <datei>  u=w,g=w
 chmod 620 <datei>  u=rw,g=w


 Okt.   Bin.

 1      001
 2      010
 4      100 

  7  6  4
 111110100
 rwxrw-r--

=== Standardberechtigungen

* auf Datei: 644
* auf Verzeichnis: 755

=== Sonderbits

==== SUID Bit 

Auf eine ausführbare Binärdatei gesetzt, bewirkt das SUID-Bit, dass die Datei mit den Berechtigungen des Besitzers (und nicht den Berechtigungen des aufrufenden Benutzers) ausgeführt wird.

Beispiel:

 /usr/bin/passwd

==== SGID Bit 

Auf eine ausführbare Binärdatei ähnlich wie das SUID-Bit, nur dass die Datei mit den Berechtigungen der Gruppe ausgeführt wird.

Auf ein Verzeichnis angewendet, sorgt das SGID-Bit dafür, dass darin neu erstellte Dateien der Gruppe des Verzeichnisses zugeordnet werden, nicht der initialien Gruppe des Benutzers, der die Datei erstellt.

Beispiel:

 /var/mail

==== Sticky Bit

Auf ein Verzeichnis gesetzt, sorgt es dafür, dass nur der Besitzer einer Datei diese ändern oder löschen darf.

Beispiel:

 /tmp

== Paketmanagement

=== Debian Paketmanagement

- `dpkg -i <datei>.deb`: Paket `<datei>` installieren (oder Update falls Paket schon installiert)
- `dpkg -I <datei>.deb`: Informationen über Paket `<datei>.deb`
- `dpkg --info <datei>.deb`: Informationen über Paket `<datei>.deb`
- `dpkg -r <paket>`: Paket `<paket>` entfernen/deinstallieren (Konfigurationsdateien bleiben erhalten)
- `dpkg -P <paket>`: Paket `<paket>` entfernen/deinstallieren (Konfigurationsdateien werden mit entfernt)
- `dpkg -l`: Liste aller auf dem System installierten Pakete inkl. Status (installiert, entfernt, teilweise installiert/entfernt ...)
- `dpkg --list`: Liste aller auf dem System installierten Pakete inkl. Status (installiert, entfernt, teilweise installiert/entfernt ...)
`dpkg -l <glob-pattern>`: Liste aller Pakete, die auf `<glob-pattern>` passen 
- `dpkg --get-selections`: übersichtliche Liste aller installierten Pakete
- `dpkg -L <paket>`: Liste aller im Paket `<paket>` enthaltener Dateien
- `dpkg --list-files <paket>`: Liste aller im Paket `<paket>` enthaltener Dateien
- `dpkg -s`: Statusinformationen aller auf dem System installierten Pakete
- `dpkg -s <paket>`: Statusinformationen von `<paket>`
- `dpkg -S /path/to/file`: Angabe, zu welchem Paket `/path/to/file/` gehört

=== Troubleshooting

Bei fehlerhaften oder nur teilweise installierten Paketen können wir folgende Option von `apt` nutzen:

 apt install -f
 apt install --fix-broken

== Paketquellen

`Archive type`:: A repository may contain packages with ready-to-run software (binary packages, type deb) or with the source code to this software (source packages, type deb-src). The example above provides binary packages.

`URL`:: The URL for the repository.

`Distribution`:: The name (or codename) for the distribution for which packages are provided. One repository may host packages for multiple distributions. In the example above, disco is the codename for Ubuntu 19.04 Disco Dingo.

`Components`:: Each component represents a set of packages. These components may be different on different Linux distributions. For example, on Ubuntu and derivatives, they are:

`main`:: contains officially supported, open-source packages.

`restricted`:: contains officially supported, closed-source software, like device drivers for graphic cards, for example.

`universe`:: contains community maintained open-source software.

`multiverse`:: contains unsupported, closed-source or patent-encumbered software.

On Debian, the main components are:

`main`:: consists of packages compliant with the Debian Free Software Guidelines (DFSG), which do not rely on software outside this area to operate. Packages included here are considered to be part of the Debian distribution.

`contrib`:: contains DFSG-compliant packages, but which depend on other packages that are not in main.

`non-free`:: contains packages that are not compliant with the DFSG.

`security`:: contains security updates.

`backports`:: contains more recent versions of packages that are in main. The development cycle of the stable versions of Debian is quite long (around two years), and this ensures that users can get the most up-to-date packages without having to modify the main core repository.

== apt-get

- `apt-get update`: Paketindex auf den neuesten Stand bringen
- `apt-get upgrade`: alle Pakete aktualisieren. Es werden aber keine neuen Pakete installiert oder vorhandene entfernt.
- `apt-get dist-upgrade`: wie `upgrade`, es werden aber ggf. neue Pakete installiert oder vorhandene entfernt.
- `apt-get remove`: Paket entfernen, Konfigurationsdateien bleiben erhalten
- `apt-get remove --purge`: Paket entfernen, Konfigurationsdateien werden mit entfernt
- `apt-get purge`: Paket entfernen, Konfigurationsdateien werden mit entfernt
- `apt-get autoremove`: alle Pakete entfernen, die automatisch installiert wurden (als Abhängigkeit) und von keinem weiteren Paket benötigt werden.
- `apt-get clean`: `.deb` Pakete löschen
- `apt-cache search`: nach Paketen suchen, akzeptiert RegEx, durchsucht Paketnamen und Beschreibung
- `apt-cache show`: Informationen über ein Paket
- `apt-file`: Muss zusätzlich installiert werden 
- `apt-file search `: Kann herausfinden, welches Paket `<datei>` bereitstellt 
- `apt-file update `: Paketindex von `apt-file` aktualiseren


== Paketmanagement Red hat

=== rpm

- kann Programme installieren, die lokal auf dem System vorliegen
- die Pakete müssen dafür in einem bestimmten Binärformat vorliegen (`.rpm`)
- Abhängigkeiten können nicht automatisch aufgelöst werden
- fehlende Abhängigkeiten werden allerdings aufgelistet (jedoch nur die Dateien
  an sich, nicht die fehlenden _Pakete_)
- `-v` verboser Output
- `-h` Hashtags (`#`) als Fortschrittsanzeige

Installation eines Pakets:

----
rpm -i PACKAGENAME
rpm -i gimp-2.8.22-1.el7.x86_64.rpm
----

=== Update

Ein Paket aktualisieren

----
rpm -U PACKAGENAME
----

- ist kein Paket mit diesem Namen vorhanden, wird es trotzdem die neues Version installiert.
- dies kann mit der Option `-F` verhindert werden

=== Deinstallation

----
rpm -e PACKAGE    # erase
rpm -e wget
----

=== Installierte Pakete anzeigen

Alle installierten Pakete anzeigen

----
rpm -qa      # query all
----

=== Informationen über Pakete erhalten

Informationen über ein installiertes Paket:

----
rpm -qi unzip       # query information
----

Informationen darüber, welche `Dateien` in einem Paket enthalten sind:

----
rpm -ql unzip      # query list
----

Informationen über ein `noch nicht` installiertes Paket, hier kann eine FTP-Adresse oder URL angegeben werden:

----
rpm -qip atom.x86_64.rpm           # query information not installed
----

----
rpm -qlp atom.x86_64.rpm     # query list not installed
----


=== Zu welchem Paket gehört eine Datei

----
rpm -qf /usr/bin/unzip       # query file
> unzip-6.0-19.el7.x86_64
----

== YellowDog Updater Modified (yum)

Unterschied zu Debian: Der Paketindex wird automatisch aktualisiert. 

=== nach Paketen suchen

----
yum search PATTERN

yum search 7zip
----

=== Installation, Upgrade, Removal

Ohne die Angabe eines Paketnamens wird das gesamte System aktualisiert. Es gibt *kein* `yum upgrade`!

----
yum update
----

----
yum install p7zip
----

----
yum update wget
----

----
yum check-update PACKAGENAME
yum check-update                # gesamtes System
----

=== Pakete nur herunterladen

----
yum install --downloadonly <package>
> yum install --downloadonly --downloaddir=<directory> <package>
----

=== zu welchem Paket gehört eine Datei

----
yum whatprovides DATEI
yum whatprovides libgimpui-2.0.so.0
----

Funktioniert auch mit Dateien:

----
yum whatprovides /etc/hosts
----

=== Informationen über ein Paket erhalten

----
yum info firefox
----

=== Software Repositories

- Repos sind in `/etc/yum.repos.d` zu finden, z.B. `CentOS-Base.repo`
- Repos können hinzugefügt werden, indem eine `.repo` Datei dort abgelegt wird (oder am Ende von `/etc/yum.conf`)
- besser aber mit dem Tool `yum-config-manager`

Um den `yum-config-manager` nutzen zu können muss das Paket `yum-utils` installiert werden.

----
yum-config-manager --add-repo https://rpms.remirepo.net/enterprise/remi.repo

yum-config-manager --enable-repo baseos-source
----

Liste der verfügbaren Repositories:

----
yum repolist all
----

Repos disablen und enablen:

----
yum-config-manager --disable <reponame>
yum-config-manager --disable updates
yum-config-manager --enable <reponame>
yum-config-manager --enable updates
----

=== Cache leeren

----
# yum clean packages
# yum clean metadata
----

= Paketmanagement bei OpenSUSE

- OpenSUSE verwednet `zypper` als Paketmanagement Tool
- ähnlich wie `apt` und `yum`

== Paketindex aktualisieren

----
zypper refresh      # Paketindex aktualisieren
----

- pro Repo kann eingestellt werden, ob der Index automatisch aktualiert werden soll

== nach Paketen suchen

----
zypper search <paketname>      # nach Paketen suche
zypper se <paketname>
zypper se -i              # Liste der installierten Pakete
zypper se -i <string>     # prüfen, ob Pakete installiert mit <string> im Namen installiert sind
zypper se -u <string>     # Suche nach nicht-installierten Paketen
----

== Installation von Paketen

----
zypper install <paketname>
zypper in <paketname>
----

- mit `zypper` können auch lokal vorhandene `.rpmr` Pakete installiert werden
- Abhängigkeiten werden dabei aufgelöst
- hier muss der absolute Pfad angegeben werden

== Upgrade von Paketen / des Systems

----
zypper update        # alle installierten Pakete aktualisieren
zypper list-updates  # alle Aktualisierungen anzeigen
----

== Löschen von Paketen

- beim Entfernen von Paketen werden automatisch alle Pakete mit entfernt, die von dem zu entfernenden Paket abhängen

----
zypper remove <paket>
zypper re <paket>
----

== Suche nach dem Paket, welches eine Datei enthält

- hierzu wird der Suchparameter `se` mit der Option `--provides` erweitert
- es folgt der absolute Pfad zur Datei

----
# zypper se --provides /usr/lib64/libgimpmodule-2.0.so.0
----

== Informationen über installierte Pakete

----
# zypper info gimp
----

== Software Repositories

- Anzeige aller auf dem System registrierten Repositories mit `zypper repos`
- mit der Option `modifyrepo` können Repos konfiguriert werden
- Repos aktivieren und deaktivieren mit `-e` und `-d`:

----
# zypper modifyrepo -d repo-non-oss
Repository 'repo-non-oss' has been successfully disabled.

# zypper modifyrepo -e repo-non-oss
Repository 'repo-non-oss' has been successfully enabled.
----

- _autorefresh_ für ein Repo ein- bzw. ausschalten mit `-f` und `-F`:

----
# zypper modifyrepo -F repo-non-oss
Autorefresh has been disabled for repository 'repo-non-oss'.

# zypper modifyrepo -f repo-non-oss
Autorefresh has been enabled for repository 'repo-non-oss'.
----

- Repos können mit `addrepo` hinzugefügt und mit `removerepo` wieder entfernt werden:

----
# zypper addrepo http://packman.inode.at/suse/openSUSE_Leap_15.1/ packman
----

- beim Hinzufügen können mit `-f` Autoupdates eingeschaltet werden
- wird beim Hinzufügen die Option `-d` mit angegeben, wird das Repo hinzugefügt aber nicht aktiviert

----
# zypper removerepo packman
----

== Integrität von Dateisystemen

Freien Speicherplatz anzeigen:

- `df`: _Disk Free_: verfügbaren Speicherplatz anzeigen
- `df -h`: verfügbaren Speicherplatz in KiB,Mib etc. anzeigen
- `df -hTx tmpfs -x devtmpfs`: 
- `df -i`: Anzeige der Inodes

Benutzten Speicherplatz anzeigen:

- `du`: _Disk Usage_: genutzten Speicherplatz anzeigen


== Scripts

=== Notationselemente

- `test -e <path>`: True, falls `<paht>` existiert
- `[ -e <path> ]`: gleich wie oben, `[ ` (Leerschritt hinter `[` ist wichtig) ist eine andere Schreibweise für das Kommando `test` 
- `set -x`: Schaltet die Option `x` (Debug Output) ab dieser Zeile ein
- `set +x`: Schaltet die Option `x` (Debug Output) ab dieser Zeile aus
- `[[ ]]`: ist eine Alternative zum `test` Kommando bzw. `[ `, bzw. ein syntaktisches Element von BASH, mit mehr Funktionen als das Kommando `test`. Z.B. werden Strings automatisch in Quotes gesetzt, wir können mit `=~` mit einem regulären Ausdruck vergleichen etc.
- `if test ...; then ... fi` : If-Verzweigung
- `if [ ... ]; then ... fi` : If-Verzweigung
- `if [[ ... ]]; then ... fi` : If-Verzweigung
- Genereller möglicher Aufbau einer If-Verzweigung:

 if [ ... ]; then 
   ... 
 elif [ ... ];then 
   ...
 else 
   ... 
 fi

- `!`: Ein Ausrufezeichen in einem `test` Kommando bzw. einer if-Bedingung, _negiert_ den Ausdruch:

 [ ! -e <paht> ] # ist TRUE, falls <path> NICHT existiert

- `read -p 'eine Frage' answer`: `eine Frage` wird ausgegeben (wie mit `echo`), die interaktiv einzugebende Anwort wird in der Variablen `answer` gespeichert
- `exit 0`: Skript wird mit Exit Code `0` (alles okay) beendet
- `exit 1`: Skript wird mit Exit Code `1` (irgendein Fehler) beendet
- `<string1> == <string2>`: String Vergleich 
- `<string> =~ <regex>`: Vergleich auf regulären Ausdruck 
- `<ausdruck 1> && <ausdruck 2>`: Logisches UND: `<ausdruck 2>` wird nur ausgeführt, wenn `<ausdruck 1>` _wahr_ ist, fehlerfrei ausgeführt werden konnte etc.
- `<ausdruck 1> || <ausdruck 2>`: Logisches ODER: `<ausdruck 2>` wird nur ausgeführt, wenn `<ausdruck 1>` _falsch_ ist, also nicht ausgeführt werden konnte etc.
















