= Übungen zu Regulären Ausdrücken

== Reguläre Ausdrücke

a) Welcher Reguläre Ausdruck passt auf jede E-Mail Adresse wie `info@example.org`?

b) Welcher Reguläre Ausdruck passt auf alle IPv4 Adressen der Form `192.168.15.1`, `10.23.22.155` etc.?

c) Wie kann mit dem  Kommando `grep` die Datei `/etc/serives` angeszeigt werden, aber ohne Kommentarzeilen?

a) Die Datei `domains.txt` enthält eine Liste von Domain Namen, einen pro Zeile. Wie kann man `egrep` ausschliesslich `.org` und `.com` Domänen anzeigen?

.domains.txt
----
mydomain.org
https://yourdomain.org
https://yourdomain.xzy
www.yourdomain.com
http://www.yourdomain.de
----

a) Wie kann man, ausgehend vom aktuellen Verzeichnis, mit dem Kommando `find` alle Dateien anzeigen, die keinen Standard Suffix haben. Also alle die, die nicht auf `.txt`, `.c`, `.pdf` etc. enden? Nutzt dafür einen Erweiterten Regulären Ausdruck.

== grep und sed

a) Das Kommando `last` zeigt eine Liste der zuletzt angemeldetetn Benutzer. Wie kann man mit dem Kommando `egrep` die Ausgabe von `last` so filtern, dass nur nur die Ausgaben mit IPv4 Adressen angezeigt werden ohne zusätzliche Informationen in der entsprechenden Zeile?

b) Das Kommando `uptime -s` zeigt das Datum, an dem das System das letzte Mal gestartet wurde, z.B. `2020-11-02 8:15:10`. Was ist wohl die Ausgabe des Kommandos 

 uptime -s | sed -e 's/(.=) (.=)/\1/'

c) Die Grundstruktur einer HTML Datei startet mit den Elementen `html`, `head` und `body`:

----
<html>
<head>
  <title>News Site</title>
</head>
<body>
  <h1>Headline</h1>
  <p>Information of interest.</p>
</body>
</html>
----

c.1) Wie kann man sich mit dem Kommando `sed` ausschliesslich die `body` Elemente inklusive Inhalt anzeigen lassen?

c.2) Welches `sed` Kommando entfernt alle HTML Tags aus dem HTML Dokument, aber nicht den eigentlichen Text/Inhalt?

d) Dateien mit der Erweiterung `.ovpn` werden genutzt, um VPN Clients zu konfigurieren. Sie enthalten dabei nicht nur die Konfiguration an sich, sondern auch die Schlüssel und Zertifikate für den Client. Diese befinden sich normalerweise in seperaten Dateien und müssen in die `.ovpn` Datei kopiert werden.

Gegeben ist folgendes `.ovpn` Template:

----
client
dev tun
remote 192.168.1.155 1194
<ca>
ca.crt
</ca>
<cert>
client.crt
</cert>
<key>
client.key
</key>
<tls-auth>
ta.key
</tls-auth>
----

Angenommen, die Dateien `files ca.crt`, `client.srt`, `client.key` und `ta.key` befinden sich im aktuellen Verzeichnis. Wie kann man mit `sed` den Inhalt der Dateien in das `.ovpn` Template kopieren, also dort jeden Dateinamen durch deren Inhalt ersetzen?
