= Übungen zu Prozessen

== Vordergrund und Hintergrund

`oneko` ist ein kleines Programm, welches eine Katze zeigt, die den Mauscursor
verfolgt. Installiert es auf eurem System.

1) Startet das Programm aus einem Terminal.

2) Bewegt den Mauszeiger und schaut was passiert. Haltet den Prozess nun an (mit `STRG-Z`). Was passiert?

3) Überprüft, wie viele Jobs momentan laufen (mit dem Kommando `jobs`)

4) Schickt das Programm nun mittels seiner Job ID in den Hintergrund (Syntax `bg %<Job ID>`). Was passiert? Wie könnt ihr prüfen, ob der Job im Hintergrund laüft?

5) Beendet nun den Prozess über die Angabe der PID mit dem Kommando `kill`.

== Prozesse ermitteln und beenden

Installiert für die folgende Übunng den Webserver `apache2` mit dem Kommanod `apt install apache2` auf eurem System.

1) Ermittelt nun alle Prozesse, die vom Apache2 erzeugt (_gespawnt_) werden. Nutzt dafür zwei verschiedene Kommandos.

2) Beendet alle laufenden Prozesse des `apache2`, ohne dabei deren PIDs zu nutzen. Macht auch dies mit zwei unterschiedlichen Kommandos.

3) Wie kann man alle Instanzen (Prozesse) des `apache2` beenden (mit dem Standardsignal `SIGTERM`) ohne vorher deren PIDs ermitteln zu müssen? Nutzt dafür ausschließlich das Kommando `kill` (*nicht* `killall`).

4) Nutzt das Kommando `ps` um euch alle Prozesse des Systembenutzers (`www-data`) des `apache2` anzeigen zu lassen. Probiert hier alle Screibweisen (Unix, BSD und Linux) aus.

== =top= und =ps=

1) `top` sortiert die Ausgabe standardmäßig nach prozentualer CPU Auslastung in
   absteigender Reihenfolge. Dieses Verhalten kann interaktiv (also während
   `top` läuft) mit den Tasten `M`, `N`, `T` und `P` beeinflusst werden.
   Probiert es aus und notiert euch, was diese Schalter bewirken.

2) Man kann `top` aber auch durch die Angabe von Optionen (`top -o <option(en)>`) beim Start zu einer gewünschten Ausgabe überreden. Startet `top` so, dass alle Prozesse nach Auslastung des Hauptspeichers sortiert werden.

3) Im laufenden `top`: Lasst euch die Hauptspeicher Spalte hervorgehoben anzeigen.

4) Die Option `o` gibt es auch für `ps`. Damit kann man sich hier bestimmte Spalten anzeigen lassen. Startet `ps` so, dass nur Informationen über den Benutzer, prozentuale
   Auslastung des Hauptspeichers, prozentuale Auslastung der CPU und das
   komplette Kommando angezeigt werden.

5) Startet `ps` nun so, dass lediglich der Benutzer und das Kommando angezeigt werden.


== Besprochene Kommandos

Für die Bearbeitung der Übungen werden eventuell nicht alle Kommandos benötigt.

----
ps
jobs
fg
bg
nohup
watch
kill
pgrep
pidof
pkill
killall
----
